import { StyleSheet, Platform } from 'react-native';
import Colors from '../../../assets/Colors';

export const conversationStyles = StyleSheet.create({
  // Main Container
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  
  // Loading State
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  
  // Header Section - Modern Gradient Design
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 8,
    minHeight: 70,
    zIndex: 100,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  headerCenter: {
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
  },
  headerTitle: {
    color: '#1E293B',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  typingText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '500',
    marginTop: 2,
  },
  
  // Profile Section - Card Design
  profileSection: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginVertical: 16,
    borderRadius: 20,
    paddingVertical: 32,
    paddingHorizontal: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 8,
    alignItems: 'center',
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 20,
    borderWidth: 4,
    borderColor: '#F1F5F9',
  },
  profileName: {
    color: '#1E293B',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  connectionText: {
    color: '#64748B',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
    paddingHorizontal: 20,
  },
  viewProfileButton: {
    backgroundColor: Colors.LIGHT_PURPLE,
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 30,
    minWidth: 140,
    alignItems: 'center',
    shadowColor: Colors.LIGHT_PURPLE,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  viewProfileText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  
  // Message List
  listContent: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    minHeight: 200,
  },
  
  // Message Bubbles - Modern Design
  messageContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginVertical: 4,
    paddingHorizontal: 4,
  },
  currentUserContainer: {
    justifyContent: 'flex-end',
  },
  messageAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 12,
    borderWidth: 2,
    borderColor: '#F1F5F9',
  },
  messageBubble: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 24,
    maxWidth: '70%',
    minWidth: 80,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  otherUserBubble: {
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  currentUserBubble: {
    backgroundColor: Colors.LIGHT_PURPLE,
    borderBottomRightRadius: 8,
  },
  messageText: {
    fontSize: 16,
    lineHeight: 15,
    top: 12,
    
    fontWeight: '400',
  },
  timestampContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    alignSelf: 'flex-end',
    marginTop: 6,
    minHeight: 16,
  },
  seenIcon: {
    marginLeft: 6,
  },
  editedText: {
    fontSize: 11,
    alignSelf: 'flex-end',
    marginRight: 8,
    fontWeight: '500',
  },
  
  // Unsent Messages
  unsentBubble: {
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 24,
    maxWidth: '70%',
    minWidth: 80,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  unsentText: {
    fontSize: 16,
    color: '#94A3B8',
    fontStyle: 'italic',
    lineHeight: 24,
  },
  
  // Chat Images
  chatImage: {
    width: 240,
    height: 240,
    borderRadius: 20,
    resizeMode: 'cover',
    maxWidth: '100%',
  },
  imageLoader: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  imageTimestampContainer: {
    position: 'absolute',
    bottom: 8,
    right: 12,
    backgroundColor: 'transparent',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  
  // Date Separators
  dateSeparatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
    marginHorizontal: 16,
  },
  dateSeparatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E2E8F0',
  },
  dateSeparatorText: {
    color: '#64748B',
    marginHorizontal: 16,
    fontSize: 13,
    fontWeight: '600',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  transientTimestamp: {
    alignSelf: 'center',
    color: '#64748B',
    fontSize: 12,
    marginBottom: 8,
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  
  // Bottom Input - Modern Design
  bottomInput: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingBottom: Platform.OS === 'ios' ? 24 : 16,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    minHeight: 80,
  },
  inputContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    borderRadius: 28,
    paddingHorizontal: 20,
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginHorizontal: 12,
    minHeight: 48,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  textInput: {
    color: '#1E293B',
    fontSize: 16,
    maxHeight: 120,
    minHeight: 24,
    lineHeight: 22,
  },
  inputAction: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  
  // Edit Mode
  editContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderTopWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    minHeight: 80,
  },
  editInput: {
    flex: 1,
    borderColor: '#E2E8F0',
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    maxHeight: 120,
    minHeight: 48,
    fontSize: 16,
  },
  editButton: {
    marginLeft: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    backgroundColor: '#F1F5F9',
    minWidth: 60,
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  
  // Modal Design
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    borderRadius: 20,
    width: '85%',
    maxWidth: 320,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
  },
  modalButton: {
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderColor: '#F1F5F9',
    alignItems: 'center',
    minHeight: 56,
  },
  modalButtonText: {
    fontSize: 17,
    color: '#1E293B',
    fontWeight: '500',
  },
  
  // Suggestions
  suggestionContainer: {
    paddingHorizontal: 24,
    paddingVertical: 32,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginVertical: 16,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 8,
  },
  suggestionTitle: {
    color: '#64748B',
    fontSize: 16,
    marginBottom: 24,
    textAlign: 'center',
    paddingHorizontal: 20,
    lineHeight: 22,
    fontWeight: '500',
  },
  suggestionRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  suggestionButton: {
    backgroundColor: '#F1F5F9',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 28,
    marginHorizontal: 8,
    marginVertical: 6,
    minWidth: 100,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  suggestionText: {
    color: Colors.LIGHT_PURPLE,
    fontSize: 15,
    fontWeight: '600',
  },
  
  // Filter System - Modern Design
  filterContainer: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderBottomWidth: 0,
    borderBottomColor: 'transparent',
    paddingVertical: 16,
    minHeight: 50,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    overflow: 'hidden',
    // Overlay glass effect
    position: 'absolute',
    left: 16,
    right: 16,
    top: 80,
    zIndex: 10,

    // Soft shadow for depth
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 12,
  },
  filterSpacer: {
    height: 94,
  
  },
  filterScrollContent: {
    paddingHorizontal: 20,
    
  },
  filterBubble: {
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: 'transparent',
    width: 56,
    height: 56,
    overflow: 'hidden',
    backgroundColor: '#F8FAFC',
  },
  selectedFilterBubble: {
    borderColor: Colors.LIGHT_PURPLE,
    backgroundColor: '#F0F4FF',
  },
  filterBubbleImage: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  
  // Filter Details
  filterDetailsContainer: {
    backgroundColor: 'rgba(37, 37, 37, 0.27)',
  
   
    padding: 10,
    minHeight: 50,

    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(100, 100, 100, 0.3)',
    overflow: 'hidden',
    // Overlay glass effect
    position: 'absolute',
    left: 16,
    right: 16,
    top: 83,
    zIndex: 10,

    // Soft shadow for depth
    shadowColor: 'rgba(100, 100, 100, 0.3)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 12,
  },
  filterDetailsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    minHeight: 44,
  },
  filterDetailsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E293B',
    flex: 1,
  },
  closeFilterButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterDetailsContent: {
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  filterDetailsImage: {
    width: 100,
    height: 100,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#F1F5F9',
  },
  filterDetailsName: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: 6,
    textAlign: 'center',
    flexWrap: 'wrap',
  },
  filterDetailsDescription: {
    fontSize: 15,
    color: '#64748B',
    textAlign: 'center',
    marginBottom: 8,
    flexWrap: 'wrap',
    lineHeight: 20,
  },
  filterDetailsPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.LIGHT_PURPLE,
    marginBottom: 12,
  },
  filterDetailsInfo: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    width: '100%',
  },
  filterDetailsInfoText: {
    fontSize: 13,
    color: '#64748B',
    marginBottom: 6,
    lineHeight: 18,
    flexWrap: 'wrap',
  },
  markAsSoldButton: {
    backgroundColor: '#27ae60',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginTop: 12,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  markAsAvailableButton: {
    backgroundColor: '#f39c12',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginTop: 12,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  markAsSoldButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  
  // Facebook-style typing indicator
  typingIndicatorContainer: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: 'transparent',
    borderTopWidth: 1,
    borderTopColor: 'transparent',
  },
  typingIndicatorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(108, 107, 107, 0.1)',
    borderBottomWidth: 0,
    borderBottomColor: 'transparent',
    paddingVertical: 8,
    paddingHorizontal: 12,
    maxWidth: 80,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: 'rgba(156, 155, 155, 0.2)',
    overflow: 'hidden',
    // Overlay glass effect
  
   

    // Soft shadow for depth
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 12,
  },
  typingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgb(128, 128, 128)',
    borderWidth: 1,
    borderColor:  'rgb(255, 253, 253)',
    marginHorizontal: 2,
  },
});
